name: Build

on: [push, pull_request]

defaults:
  run:
    shell: bash --noprofile --norc -xeo pipefail {0}

jobs:

  build_wheel:

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install cibuildwheel
        run: python -m pip install -U cibuildwheel

      - name: Build wheels
        env:
          CIBW_BUILD: "cp3?-*"
          CIBW_SKIP: "*-manylinux_i686 *-win32"
          CIBW_BUILD_VERBOSITY: "1"
          CIBW_ENVIRONMENT_LINUX: "CFLAGS=-g0 LDFLAGS=-Wl,-strip-debug"
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux2014"
          CIBW_BEFORE_ALL_LINUX: "yum install -y libudev-devel"
          CIBW_BEFORE_TEST: "pip install pytest"
          CIBW_TEST_COMMAND: "pytest {project}/tests"
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Wheels (${{ runner.os }})
          path: wheelhouse/*
